CUMULUS-3805: Dashboard: display and sort records on Updated timestamp
cumulus-nasa/cumulus-dashboard pull request #1138
Opened 2024-07-23 19:51 UTC by Nnaga1

**Summary:** Summary of changes

Addresses [CUMULUS-3085 Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3805)

## Changes

- updated Dashboard pages to display and sort on Updated field instead of createdAt or timestamp

## PR Checklist

- [x] Update CHANGELOG
- [x] Unit tests
- [x] Adhoc testing
- [x] Integration tests

2024-07-31 15:08 UTC, etcart approved these changes
this looks good, one nit, but good to go

2024-07-31 15:08 UTC, etcart commented on CHANGELOG.md
> +- **CUMULUS-3805**
nit: maybe removal of the duration column should be noted here?

2024-07-31 18:57 UTC, jennyhliu requested changes
1. The tables (utils/table-config) should access updatedAt field instead of createdAt or timestamp.
2. sort by createdAt or timestamp should be changed to updatedAt

2024-08-02 14:21 UTC, jennyhliu reviewed
Update test/components/table/list-view.js
initialSortId="timestamp" to initialSortId="updatedAt"

2024-08-02 15:05 UTC, jennyhliu commented on app/src/js/utils/table-config/providers.js
>      Header: 'Last Updated',
Change to Updated to be consistent with other pages.

2024-08-05 17:47 UTC, jennyhliu approved these changes
Nice work

2024-08-05 18:18 UTC, merged